on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout from codebase
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Read mod_version from gradle.properties
        id: get_version
        run: |
          mod_version=$(grep '^mod_version=' gradle.properties | cut -d'=' -f2)
          echo "mod_version=$mod_version" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check_tag
        run: |
          mod_version=${{ steps.get_version.outputs.mod_version }}
          if git ls-remote --tags origin | grep -q "refs/tags/$mod_version"; then
            echo "Tag $mod_version already exists"
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag $mod_version does not exist"
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Exit if tag exists
        if: ${{ steps.check_tag.outputs.tag_exists == 'true' }}
        run: exit 0

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew clean build

      - name: Publish to CurseForge and GitHub Releases
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1071634
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: ${{ steps.get_version.outputs.mod_version }}
